export const colors = {
	COLOR_PRIMARY: "#e9147f",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#e9147f",
	COLOR_DARK_ALT: "#262626",
};


export const categories = [
	{
		id: "01",
		category: "Breakfast",
	},
	{
		id: "02",
		category: "Lunch",
	},
	{
		id: "03",
		category: "Dinner",
	},
];

export const recipeList = [
	{
		id: "01",
		name: "Roasted Broccoli",
		image: require("../assets/images/roasted-broccoli.jpg"),
		rating: "4.2",
		ingredients: ["40 ounces broccoli", "1 tablespoon olive oil", "salt and ground black pepper to taste"],
		time: "30 mins",
		difficulty: "Easy",
		calories: "63 cal",
		color: "#e9147f",
		description:
			"This easy roasted broccoli is easy to make and will satisfy even the pickiest eaters. ",
		steps: [
			"Preheat the oven to 400 degrees F (200 degrees C).",
			"Cut broccoli florets from the stalk.",
			"Peel the stalk and slice into 1/4-inch slices. Mix florets and stem pieces with olive oil in a bowl and transfer to a baking sheet; season with salt and pepper.",
			"Roast in the preheated oven until broccoli is tender and lightly browned, about 18 to 20 minutes.",
			"Serve and enjoy!",
		],
	},
	{
		id: "02",
		name: "Pesto Pasta",
		image: require("../assets/images/pestopasta.png"),
		rating: "3.6",
		ingredients: [
			"1 (16 ounce) package pasta",
			"2 tablespoons olive oil",
			"½ cup chopped onion",
			"2 ½ tablespoons pesto",
            "salt to taste",
            "ground black pepper to taste",
            "2 tablespoons grated Parmesan cheese",
		],
		time: "15 mins",
		difficulty: "Medium",
		calories: "225 cal",
		color: "#e9147f",
		description:
			"A flavorful Italian dish consisting of pasta coated in a vibrant basil-based sauce.",
		steps: [
			"Fill a large pot with lightly salted water and bring to a rolling boil. Stir in pasta and return to a boil.",
			"Cook pasta uncovered, stirring occasionally, until tender yet firm to the bite, about 8 to 10 minutes. Drain and transfer into a large bowl.",
			"Meanwhile, heat oil in a frying pan over medium-low heat. Add onion; cook and stir until softened, about 3 minutes.",
			"Stir in pesto, salt, and pepper until warmed through.",
            "Add pesto mixture to hot pasta; stir in grated cheese and toss well to coat.",
			"Let it cool slightly before serving.",
		],
	},
	{
		id: "03",
		name: "Indian Egplant- Burtha",
		image: require("../assets/images/burtha.png"),
		rating: "4.6",
		ingredients: ["1 eggplant", "2tbps vegetable oil", "½ teaspoon cumin seeds", "1 medium onion, sliced", "1 teaspoon chopped fresh ginger", "1 large tomato - peeled, seeded and diced", "1 clove garlic, minced", "½ teaspoon ground turmeric", "½ teaspoon ground cumin", "½ teaspoon ground coriander", "¼ teaspoon cayenne pepper", "½ teaspoon salt, or to taste", "ground black pepper to taste", "¼ cup chopped fresh cilantro"],
		time: "1 hr 5 minutes",
		difficulty: "Difficult",
		calories: "120 cal",
		color: "#e9147f",
		description:
			"A spiced and mashed eggplant dish cooked with onions, tomatoes, and aromatic spices, offering a rich and smoky flavor profile.",
		steps: [
			"Preheat the oven's broiler. Rub oil on the outside of the egg plant, or coat with cooking spray.",
			"Place under the broiler, and cook until the flesh is soft and the skin is blistering off, about 30 minutes. Turn as needed for even cooking.",
			"Cut the eggplant in half lengthwise, and scoop the flesh out of the skin. Discard the skin; chop up the flesh, and set aside.",
			"Heat the oil in a large skillet or wok over medium-high heat. Add the cumin seeds, and let them crackle for a few seconds and turn golden brown. Be careful not to burn them.",
            "Add the onion, ginger and garlic; cook and stir until tender. I don't let the onions get very brown.",
            "Stir in the tomato, and season with turmeric, ground cumin, ground coriander, cayenne pepper, salt and black pepper. Cook and stir for a few minutes.",
            "Place the eggplant pieces in the skillet, and cook for 10 to 15 minutes so some of the moisture evaporates.",
            "Taste, and adjust seasonings if desired. Garnish with fresh cilantro, and serve.",
		],
	},
	{
		id: "03",
		name: "Mexican pizza",
		image: require("../assets/images/pizza.png"),
		rating: "3.6",
		ingredients: ["1/2 pound ground beef", "1 medium onion, diced", "1 clove garlic, minced", "1 tbsp chili powder", "1 tbsp ground cumin", "1/2 tbsp paprika", "1/2 tbsp salt", "1/2 tbsp black pepper", "1(16 ounce) can refried beans", "4(10 inch) flour tortillas", "1/2 cup salsa", "1 cup shredded Monterey Jack cheese", "1 cup shredded Cheddar cheese", "2 green onions, chopped", "2 tomatoes, diced", "1/4 cup thinly sliced jalapeno pepper", "1/4 cup sour cream(Optional)"],
		time: "45 mins",
		difficulty: "Medium",
		calories: "370 cal",
		color: "#e9147f",
		description:
			"This Mexican pizza recipe layers delicious seasoned ground beef and refried beans between two crisp tortillas. Top with salsa, cheese, tomatoes, and jalapeño for incredible flavor in every bite!",
		steps: [
			"Preheat the oven to 350 degrees F (175 degrees C). Coat 2 pie plates with non-stick cooking spray.",
			"Place ground beef, onion, and garlic in a skillet over medium heat. Cook until beef is evenly browned and crumbly, 5 to 7 minutes.",
			"Drain and discard grease. Season beef with chili powder, cumin, paprika, salt, and pepper.",
			"Lay one tortilla in each pie plate, and cover with a layer of refried beans. Spread 1/2 of the seasoned ground beef over each one, and then cover with a second tortilla. Bake in the preheated oven until tortillas are crisp, about 10 minutes.",
			"Remove pizzas from the oven and set aside to cool slightly. Then spread 1/2 of the salsa over each top tortilla. Cover each pizza with 1/2 of the Cheddar and Monterey Jack cheeses. Place 1/2 of the tomatoes, 1/2 of the green onions, and 1/2 of the jalapeño slices onto each one.",
            "Return pizzas to the oven and bake until cheese is melted, about 5 to 10 more minutes. Let pizzas cool slightly before slicing each one into 4 pieces.",
		],
	},
	{
		id: "03",
		name: "Fried Chicken",
		image: require("../assets/images/chicken.png"),
		rating: "2.2",
		ingredients: ["30 saltine crackers", "2 tablespoons all-purpose flour", "2 tablespoons dry potato flakes", "1 teaspoon seasoned salt", "½ teaspoon ground black pepper", "1 egg", "6 skinless, boneless chicken breast halves", "2 cups vegetable oil for frying"],
		time: "45 mins",
		difficulty: "Medium",
		calories: "887 cal",
		color: "#e9147f",
		description:
			"A fun chicken recipe the kids can help prepare. They love crushing the crackers. It does not matter if the measurements aren't perfect, just wing it!",
		steps: [
			"Place crackers in a large resealable plastic bag; seal bag and crush crackers with a rolling pin until they are coarse crumbs.",
			"Add the flour, potato flakes, seasoned salt, and pepper and mix well.",
			"Beat egg in a shallow dish or bowl. One by one, dredge chicken pieces in egg, then place in bag with crumb mixture. Seal bag and shake to coat",
			"Heat oil in a deep-fryer or large saucepan to 350 degrees F (175 degrees C)",
			"Fry chicken, turning frequently, until golden brown and juices run clear, 15 to 20 minutes.",
			"Serve hot and enjoy your flavorful chicken!",
		],
	},
	{
		id: "02",
		name: "Chocolate Cupcakes",
		image: require("../assets/images/cupcakes.png"),
		rating: "5.0",
		ingredients: ["3 cups all-purpose flour", "2 cups white sugar", "½ cup unsweetened cocoa powder", "1 teaspoon salt", "2 teaspoons baking soda", "⅔ cup vegetable oil", "2 cups water", "2 tablespoons vinegar", "2 teaspoons vanilla extract", "1 (8 ounce) package cream cheese, softened", "1 egg", "½ cup white sugar", "¼ teaspoon salt", "1 cup semisweet chocolate chips"],
		time: "55 mins",
		difficulty: "Medium",
		calories: "265 cal",
        color: "#e9147f",
		description:
			"Delightful cupcakes made with a perfect blend of flour, sugar, eggs, and chocolate, perfect for any occasion.",
		steps: [
			"Preheat the oven to 350 degrees F (175 degrees C). Line 24 muffin cups with paper liners.",
			"Mix together flour, 2 cups sugar, cocoa, 1 teaspoon salt, and baking soda in a large bowl.",
			"Stir in oil, water, vinegar, and vanilla until blended. Pour mixture into the prepared muffin cups, filling each 2/3 full.",
			"Beat together cream cheese, egg, 1/2 cup sugar, and 1/4 teaspoon salt in a medium bowl until light and fluffy.",
			"Stir in chocolate chips until incorporated. Drop a heaping teaspoonful of cream cheese mixture into each cupcake.",
			"Bake in the preheated oven until cupcake centers bounce back when gently pressed, about 25 minutes. Allow to cool before serving.",
            "Serve and enjoy!",
		],
	},
	{
		id: "02",
		name: "Thai curry soup",
		image: require("../assets/images/curry.png"),
		rating: "4.8",
		ingredients: ["2 ounces rice noodles (pad thai noodles)", "1 tablespoon olive oil", "1 clove garlic, minced", "1 ½ tablespoons minced lemongrass", "1 teaspoon ground ginger", "2 teaspoons red curry paste", "1 (32 ounce) carton chicken broth", "2 tablespoons soy sauce", "1 tablespoon white sugar", "1 (13.5 ounce) can reduced-fat coconut milk", "1 (10 ounce) bag baby spinach leaves", "½ cup peeled and deveined medium shrimp", "½ cup sliced mushrooms", "¼ cup chopped cilantro", "2 tablespoons fresh lime juice", "2 green onions, thinly sliced"],
		time: "55 mins",
		difficulty: "Hard",
		calories: "247 cal",
		color: "#e9147f",

		description:
			"This delicious Thai-style soup has coconut milk, shrimp, mushrooms, and spinach.",
		steps: [
			"Bring a large pot of lightly salted water to a boil. Add rice noodles and cook until tender yet firm to the bite, about 3 minutes. Drain and rinse well with cold water to stop the cooking; set aside.",
			"Heat oil in a large saucepan over medium heat. Stir in garlic, lemongrass, and ginger; cook and stir until aromatic, 30 to 60 seconds. Add curry paste and cook for 30 seconds.",
			"Pour in about 1/2 cup chicken broth and stir until curry paste has dissolved, then add soy sauce, sugar, and remaining chicken broth. Bring to a boil, then reduce the heat to medium-low. Cover partially and simmer for 20 minutes.",
			"Stir in coconut milk, spinach, shrimp, mushrooms, cilantro, and lime juice. Increase the heat to medium-high and simmer until shrimp are bright pink on the outside and the meat is opaque, about 5 minutes.",
			"To serve, place some rice noodles into each serving bowl and ladle soup over the top. Garnish each bowl with a sprinkling of sliced green onion.",		],
	},
	{
		id: "02",
		name: "Spaghetti",
		image: require("../assets/images/Spaghetti.png"),
		rating: "4.2",
		ingredients: ["1 spaghetti squash, halved lengthwise and seeded", "2 tablespoons vegetable oil", "1 onion, chopped", "1 clove garlic, minced", "1 ½ cups chopped tomatoes", "¾ cup crumbled feta cheese", "3 tablespoons sliced black olives", "2 tablespoons chopped fresh basil"],
		time: "45 mins",
		difficulty: "Medium",
		calories: "147 cal",
		color: "#e9147f",
		description:
			"A long, thin pasta, typically served with a variety of sauces, ranging from marinara to carbonara, providing a versatile and satisfying meal option.",
		steps: [
			"Preheat the oven to 350 degrees F (175 degrees C). Lightly grease a baking sheet.",
			"Place spaghetti squash cut-sides down on the prepared baking sheet. Bake in the preheated oven until a sharp knife can be inserted with only a little resistance, about 30 minutes.",
			"Remove squash from oven and set aside to cool enough to be easily handled.",
			"Meanwhile, heat oil in a skillet over medium heat. Cook and stir onion in oil until tender. Add garlic; cook and stir until fragrant, 2 to 3 minutes. Stir in tomatoes and cook until tomatoes are warmed through.",
			"Serve and enjoy!",
		],
	},
];